### PR TITLE
readme + image

### PR DESCRIPTION
**Pull request by hoffmannjan**

### CODE REVIEW

**Comment by CWOP** [comment]
jan:  I no longer do any Arduino at all.  so please ignore/ remove me from anything to do with Arduino, adafruit, etc.  this stuff has gotten way beyond me.  and I am just not interested any more.  chip  modesto ca

former adafruit/ Arduino experimenter

From: Jan Hoffmann 
Sent: Friday, March 15, 2019 7:06 AM
To: adafruit/Adafruit_Proto-Screwshield 
Cc: Subscribed 
Subject: [adafruit/Adafruit_Proto-Screwshield] readme + image (#1)


--------------------------------------------------------------------------------

You can view, comment on, or merge this pull request online at:
  https://github.com/adafruit/Adafruit_Proto-Screwshield/pull/1

Commit Summary
  a.. readme + image 
File Changes
  a.. A README.md (16) 
  b.. A assets/board.jpg (0) 
Patch Links:
  a.. https://github.com/adafruit/Adafruit_Proto-Screwshield/pull/1.patch 
  b.. https://github.com/adafruit/Adafruit_Proto-Screwshield/pull/1.diff

**Comment by ladyada** [comment]
@CWOP hi, you clicked WATCH on this repo to watch it. you will get emails until you unwatch the repo

image

nothing we can do about it - you must unsubscribe ;)

**Review by ladyada — APPROVED** [review]

**Comment by CWOP** [comment]
HOW DO I DO THAT?

**Comment by CWOP** [comment]
HOW THE HELL DO I SHUT THIS DAMN COMPUTER GOBBLY GOOK OFF???????????????????  I DO NOT UNDERSTAND.

I DO NOT UNDERSTAND GITHUB EITHER.  HOW THE HECK DO I SHUT IT OFF TOO?
I AM ADDING TO BLOCKED SENDERS LIST HERE ON MY EMAIL  TO DUMP ALL THIS GARBAGE SO I DO NOT SEE THIS COMPUTER CRAP!!!

NOT SEEN ANY OF THIS FOR SEVERAL YEARS, WHY NOW?

**Comment by ladyada** [comment]
ok i blocked 'em - github is the new mailing list!

**Pull request merged**
